// types/journal.ts
// Shared type definitions for the Journal content system.
// In production: ArticleSummary and FullArticle are generated by contentlayer
// from MDX frontmatter. The shapes here are the migration target  -  when
// contentlayer is added, these types will be replaced with contentlayer's
// generated types, and the import paths updated accordingly.

import type { JournalCategory } from "@/lib/constants";

// ─── Image asset ─────────────────────────────────────────────────────────────

export type ArticleImage = {
  readonly src:     string;
  readonly alt:     string;
  readonly caption?: string; // Optional short editorial caption, separate from alt
  readonly position?: string;
  readonly fit?: "cover" | "contain";
  readonly maxWidthPx?: number;
};

export type ArticleInline =
  | { readonly type: "text"; readonly text: string }
  | { readonly type: "link"; readonly text: string; readonly href: string; readonly external?: boolean }
  | { readonly type: "em"; readonly text: string }
  | { readonly type: "strong"; readonly text: string };

// ─── Article summary ─────────────────────────────────────────────────────────
// Used on the Journal index and wherever articles appear in lists.
// Does not include body content.

export type ArticleSummary = {
  readonly slug:        string;
  readonly title:       string;
  readonly category:    JournalCategory;
  readonly excerpt:     string;
  readonly readingTime: number;
  readonly publishedAt: string; // ISO 8601  -  "2024-10-15"
  readonly img?:        ArticleImage;
};

// ─── Article body block ───────────────────────────────────────────────────────
// In production: replaced by compiled MDX  -  this union type scaffolds the
// layout before the MDX pipeline is in place. Each type maps 1:1 to the
// prose styles used in the article body renderer.

export type ArticleBodyBlock =
  | { type: "p-lead";     text?: string; content?: readonly ArticleInline[] }
  | { type: "p";          text?: string; content?: readonly ArticleInline[] }
  | { type: "h2";         text: string }
  | { type: "h3";         text: string }
  | { type: "blockquote"; text?: string; content?: readonly ArticleInline[] }
  | {
      type: "image";
      image: ArticleImage;
      description?: string;
      aspect?: string;
    }
  | {
      type: "table";
      caption?: string;
      columns: readonly string[];
      rows: readonly {
        readonly cells: readonly string[];
      }[];
    };

// ─── Related journey reference ────────────────────────────────────────────────
// Lightweight reference  -  only what the article body renderer needs.
// Full journey data is sourced from the journey content system.

export type RelatedJourneyRef = {
  readonly slug:    string;
  readonly name:    string;
  readonly outcome: string;
  readonly img:     ArticleImage;
};

// ─── Full article ─────────────────────────────────────────────────────────────
// Used on individual article pages. Extends ArticleSummary with body and
// relational fields.

export type FullArticle = ArticleSummary & {
  readonly subtitle?:        string;
  readonly seoTitle?:        string;
  readonly openGraphTitle?:  string;
  readonly openGraphDescription?: string;
  readonly metaTitle?:       string;
  readonly metaDescription?: string;
  readonly body:             readonly ArticleBodyBlock[];
  readonly relatedJourneys?: readonly RelatedJourneyRef[];
  readonly relatedArticles?: readonly ArticleSummary[];
};
